apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-apk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-apk
  template:
    metadata:
      labels:
        app: nginx-apk
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: apk-vol
          mountPath: /usr/share/nginx/html
      volumes:
      - name: apk-vol
        hostPath:
          path: /opt/apks
          type: Directory
